name: freedom-guard
version: '1.4.5'
summary: Freedom Guard is a tool for bypassing internet censorship.
description: |
  Freedom Warp+, Freedom Vibe+, Freedom Browser+

base: core20
confinement: strict

parts:
  freedom-guard:
    plugin: nodejs
    source: .
    build-packages:
      - build-essential
      - libgtk-3-dev
      - libx11-dev
      - libdbus-1-dev
    stage-packages:
      - libgconf-2-4
    override-build: |
      npm install
      npm run build

apps:
  freedom-guard:
    command: desktop-launch $SNAP/bin/freedom-guard
    plugs:
      - network
      - network-bind
      - x11
      - desktop
      - unity7
      - gsettings
      - pulseaudio
      - opengl
